services:
  - type: web
    name: emotion-detector
    env: python
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: HF_API_KEY
        value: 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